import { expect, test } from "bun:test";
import { getCommandMatches, SLASH_COMMANDS } from "./commands";

test("command palette lists only implemented command families", () => {
  const commands = SLASH_COMMANDS.map((item) => item.command);

  expect(commands).toContain("/agent");
  expect(commands).toContain("/lane");
  expect(commands).toContain("/lane cloud-mcp");
  expect(commands).toContain("/lane mcp");
  expect(commands).toContain("/lane native-mcp");
  expect(commands).toContain("/model");
  expect(commands).toContain("/model cloud-mcp");
  expect(commands).toContain("/mcp");
  expect(commands).toContain("/mcp catalog");
  expect(commands).toContain("/mcp on");
  expect(commands).toContain("/mcp off");
  expect(commands).toContain("/review");
  expect(commands).toContain("/checkpoint");
  expect(commands).toContain("/edit");
  expect(commands).toContain("/memory");
  expect(commands).toContain("/index");
  expect(commands).toContain("/search");
  expect(commands).toContain("/trace");
  expect(commands).toContain("/trace export");
  expect(commands).toContain("/quickstarts");
  expect(commands).toContain("/rules");
  expect(commands).toContain("/create-rule");
  expect(commands).toContain("/engines");
  expect(commands).toContain("/engine-bay");
  expect(commands).toContain("/creative");
  expect(commands).toContain("/web");
  expect(commands).toContain("/create-engine");
  expect(commands).toContain("/create-mcp");
  expect(commands).toContain("/toolbox");
  expect(commands).toContain("/skills");
  expect(commands).toContain("/create-skill");
  expect(commands).toContain("/plugins");
  expect(commands).toContain("/plugins inspect");
  expect(commands).toContain("/create-plugin");
  expect(commands).toContain("/collapse");

  expect(commands).not.toContain("/backend");
  expect(commands).not.toContain("/git-status");
  expect(commands).not.toContain("/workspace");
  expect(commands).not.toContain("/repo-report");
});

test("command palette searches commands, examples, descriptions, and categories", () => {
  expect(getCommandMatches("/backend").map((item) => item.command)).toContain("/agent");
  expect(getCommandMatches("/diff").map((item) => item.command)).toContain("/review");
  expect(getCommandMatches("/stash").map((item) => item.command)).toContain("/checkpoint");
  expect(getCommandMatches("/session").map((item) => item.command)).toContain("/sessions");
  expect(getCommandMatches("/memory").map((item) => item.command)).toContain("/memory");
  expect(getCommandMatches("/knowledge").map((item) => item.command)).toContain("/index");
  expect(getCommandMatches("/snippet").map((item) => item.command)).toContain("/search");
  expect(getCommandMatches("/receipt").map((item) => item.command)).toContain("/trace");
  expect(getCommandMatches("/rule").map((item) => item.command)).toContain("/rules");
  expect(getCommandMatches("/rule").map((item) => item.command)).toContain("/create-rule");
  expect(getCommandMatches("/quick").map((item) => item.command)).toContain("/quickstarts");
  expect(getCommandMatches("/mcp").map((item) => item.command)).toContain("/mcp");
  expect(getCommandMatches("/mcp").map((item) => item.command)).toContain("/mcp on");
  expect(getCommandMatches("/cloud-mcp").map((item) => item.command)).toContain("/lane cloud-mcp");
  expect(getCommandMatches("/cloud-mcp").map((item) => item.command)).toContain("/model cloud-mcp");
  expect(getCommandMatches("/engine").map((item) => item.command)).toContain("/engines");
  expect(getCommandMatches("/engine").map((item) => item.command)).toContain("/create-engine");
  expect(getCommandMatches("/hub").map((item) => item.command)).toContain("/engine-bay");
  expect(getCommandMatches("/writing").map((item) => item.command)).toContain("/creative");
  expect(getCommandMatches("/url").map((item) => item.command)).toContain("/web");
  expect(getCommandMatches("/skill").map((item) => item.command)).toContain("/toolbox");
  expect(getCommandMatches("/skill").map((item) => item.command)).toContain("/skills");
  expect(getCommandMatches("/skill").map((item) => item.command)).toContain("/create-skill");
  expect(getCommandMatches("/plugin").map((item) => item.command)).toContain("/plugins");
  expect(getCommandMatches("/plugin").map((item) => item.command)).toContain("/create-plugin");
  expect(getCommandMatches("/panel").map((item) => item.command)).toContain("/collapse");
});
