import path from "node:path";
import fs from "node:fs/promises";
import { existsSync } from "node:fs";
import { userConfigDir, workspaceStorageDir } from "../config/paths";

export type GuideKind = "quickstart" | "rule";
export type GuideSource = "builtin" | "user" | "workspace";

export type Guide = {
  id: string;
  title: string;
  description: string;
  kind: GuideKind;
  triggers: string[];
  source: GuideSource;
  path: string;
  body: string;
};

export type RuleDraftAnswers = {
  name: string;
  trigger: string;
  rule: string;
  appliesTo: string;
  scope: string;
};

export type PendingRuleDraft = {
  id: string;
  name: string;
  content: string;
  savePath: string;
};

const BUILTIN_GUIDES: Guide[] = [
  {
    id: "tool-use-quick-start",
    title: "Tool Use Quick Start",
    description: "Default tool lane behavior for local coding work.",
    kind: "quickstart",
    triggers: ["tools", "files", "edit", "command", "shell", "tests", "build"],
    source: "builtin",
    path: "builtin/tool-use-quick-start",
    body: [
      "- Read files and list directories before changing code.",
      "- Prefer targeted `apply_patch` edits over full rewrites.",
      "- Run focused verification after code changes: typecheck, tests, or build.",
      "- Use approvals only for destructive, privileged, publishing, or broad external-impact actions.",
      "- Keep tool summaries concise; put detailed traces in the tool panel, not the main answer.",
    ].join("\n"),
  },
  {
    id: "web-research-quick-start",
    title: "Web Research Quick Start",
    description: "How Bay should use the guarded Web Engine.",
    kind: "quickstart",
    triggers: ["web", "latest", "current", "url", "docs", "source", "verify online"],
    source: "builtin",
    path: "builtin/web-research-quick-start",
    body: [
      "- Use `web_fetch`, `web_headers`, or `web_links` only for explicit public URLs.",
      "- Cite the URL when web-fetched facts affect the answer.",
      "- Say when a page could not be fetched, was truncated, or lacked evidence.",
      "- Do not imply live verification unless a web tool succeeded.",
    ].join("\n"),
  },
  {
    id: "mcp-lane-quick-start",
    title: "Switchbay MCP Quick Start",
    description: "How Bay should handle Switchbay MCP bridge setup and failures.",
    kind: "quickstart",
    triggers: ["mcp", "lm studio", "local tools", "browser tools", "plugin"],
    source: "builtin",
    path: "builtin/mcp-lane-quick-start",
    body: [
      "- The MCP config defaults to `~/.switchbay/lmstudio.mcp.json`.",
      "- Only trusted catalog integrations should be generated by Bay.",
      "- Switchbay MCP bridge is enabled with `/mcp on` or `SWITCHBAY_TOOL_MODE=switchbay-mcp`.",
      "- Cloud and local model lanes can both use Switchbay's normal tool bridge.",
      "- LM Studio native MCP is legacy/experimental and is selected explicitly with `/lane native-mcp`.",
      "- Missing plugin handle errors usually come from LM Studio native MCP, not Switchbay's bridge.",
    ].join("\n"),
  },
  {
    id: "engine-bay-quick-start",
    title: "Engine Bay Quick Start",
    description: "How Bay should use swappable engines.",
    kind: "quickstart",
    triggers: ["engine", "engine bay", "toolbox", "tool call", "run engine"],
    source: "builtin",
    path: "builtin/engine-bay-quick-start",
    body: [
      "- Use `list_engines` before assuming an engine exists.",
      "- Use `list_engine_tools` before running an engine tool.",
      "- Respect engine-level approval settings.",
      "- If an engine is absent, explain how to sync or configure it instead of inventing tools.",
    ].join("\n"),
  },
  {
    id: "local-first-rule",
    title: "Local First Rule",
    description: "Default operating rule for Switchbay sessions.",
    kind: "rule",
    triggers: ["default", "workspace", "repo", "local"],
    source: "builtin",
    path: "builtin/local-first-rule",
    body: [
      "- Treat the current workspace as the active world.",
      "- Do not cross into sibling repos, host services, or private infrastructure unless the user asks.",
      "- Prefer repo patterns and existing helpers over new abstractions.",
    ].join("\n"),
  },
];

export function ruleDraftPath(answers: RuleDraftAnswers, cwd = process.cwd()): string {
  const id = slugify(answers.name || "custom-rule");
  const scope = answers.scope.trim().toLowerCase();
  const root = scope.includes("workspace")
    ? path.join(workspaceStorageDir(cwd), "rules")
    : path.join(userConfigDir(), "rules");
  return path.join(root, `${id}.rule.md`);
}

export function generateRuleDraft(answers: RuleDraftAnswers, cwd = process.cwd()): PendingRuleDraft {
  const id = slugify(answers.name || "custom-rule");
  const title = answers.name.trim() || "Custom Rule";
  const triggers = splitList(answers.trigger || answers.appliesTo || title);
  const content = [
    "---",
    `id: ${id}`,
    `title: ${title}`,
    "kind: rule",
    `description: ${oneLine(answers.appliesTo || answers.rule || "Custom Switchbay operating rule.")}`,
    `triggers: [${triggers.join(", ")}]`,
    "---",
    "",
    `# ${title}`,
    "",
    "## Applies When",
    "",
    answers.appliesTo.trim() ? `- ${answers.appliesTo.trim()}` : `- ${triggers.join(", ") || "This rule is relevant."}`,
    "",
    "## Rule",
    "",
    ...answers.rule.split("\n").map((line) => line.trim()).filter(Boolean).map((line) => `- ${line.replace(/^[-*]\s*/, "")}`),
    "",
  ].join("\n");

  return {
    id,
    name: title,
    content,
    savePath: ruleDraftPath(answers, cwd),
  };
}

export async function loadGuides(cwd = process.cwd()): Promise<Guide[]> {
  const userRoot = userConfigDir();
  const workspaceRoot = workspaceStorageDir(cwd);
  const [userQuickstarts, userRules, workspaceQuickstarts, workspaceRules] = await Promise.all([
    loadGuidesFromDir(path.join(userRoot, "quickstarts"), "quickstart", "user"),
    loadGuidesFromDir(path.join(userRoot, "rules"), "rule", "user"),
    loadGuidesFromDir(path.join(workspaceRoot, "quickstarts"), "quickstart", "workspace"),
    loadGuidesFromDir(path.join(workspaceRoot, "rules"), "rule", "workspace"),
  ]);

  return mergeGuides([
    ...BUILTIN_GUIDES,
    ...userQuickstarts,
    ...userRules,
    ...workspaceQuickstarts,
    ...workspaceRules,
  ]);
}

export async function describeGuides(cwd = process.cwd(), kind?: GuideKind): Promise<string> {
  const guides = (await loadGuides(cwd)).filter((guide) => !kind || guide.kind === kind);
  const title = kind === "rule" ? "Rules" : kind === "quickstart" ? "Quick Starts" : "Quick Starts And Rules";
  const lines = [
    title,
    `User rules: ${path.join(userConfigDir(), "rules")}`,
    `User quick starts: ${path.join(userConfigDir(), "quickstarts")}`,
    `Workspace rules: ${path.join(workspaceStorageDir(cwd), "rules")}`,
    `Workspace quick starts: ${path.join(workspaceStorageDir(cwd), "quickstarts")}`,
    "",
    ...guides.map((guide) => `- \`${guide.id}\` [${guide.source}/${guide.kind}] ${guide.title}: ${guide.description}`),
  ];
  return lines.join("\n");
}

export async function buildGuidesPromptBlock(cwd = process.cwd(), maxGuides = 8): Promise<string> {
  const guides = await loadGuides(cwd);
  if (!guides.length) return "";
  const selected = guides.slice(0, maxGuides);
  const parts = selected.map((guide) => [
    `### ${guide.title} (${guide.id}; ${guide.source}/${guide.kind})`,
    guide.description,
    `Use when: ${guide.triggers.slice(0, 8).join(", ") || "the task matches this guide"}.`,
    limitLines(guide.body, 7),
  ].filter(Boolean).join("\n"));

  return `\n\nQUICK STARTS AND RULES (read before matching tool/lane work):\n${parts.join("\n\n")}`;
}

async function loadGuidesFromDir(dir: string, kind: GuideKind, source: GuideSource): Promise<Guide[]> {
  if (!existsSync(dir)) return [];
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const guides: Guide[] = [];
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".md")) continue;
    try {
      const absolute = path.join(dir, entry.name);
      const content = await fs.readFile(absolute, "utf-8");
      guides.push(parseGuideMarkdown(content, absolute, kind, source));
    } catch {
      // Ignore malformed local guide files.
    }
  }
  return guides;
}

function parseGuideMarkdown(content: string, filePath: string, fallbackKind: GuideKind, source: GuideSource): Guide {
  const { meta, body } = parseFrontmatter(content);
  const fallbackId = path.basename(filePath).replace(/\.rule\.md$|\.quickstart\.md$|\.md$/i, "");
  const title = body.match(/^#\s+(.+)$/m)?.[1]?.trim();
  return {
    id: stringMeta(meta.id, fallbackId),
    title: stringMeta(meta.title, title ?? fallbackId),
    description: stringMeta(meta.description, ""),
    kind: meta.kind === "quickstart" || meta.kind === "rule" ? meta.kind : fallbackKind,
    triggers: listMeta(meta.triggers, []),
    source,
    path: filePath,
    body: body.trim(),
  };
}

function parseFrontmatter(content: string): { meta: Record<string, string>; body: string } {
  if (!content.startsWith("---\n")) return { meta: {}, body: content };
  const end = content.indexOf("\n---", 4);
  if (end === -1) return { meta: {}, body: content };
  const raw = content.slice(4, end).trim();
  const body = content.slice(end + 4).replace(/^\n/, "");
  const meta: Record<string, string> = {};
  for (const line of raw.split("\n")) {
    const index = line.indexOf(":");
    if (index === -1) continue;
    const key = line.slice(0, index).trim();
    const value = line.slice(index + 1).trim();
    if (key) meta[key] = value;
  }
  return { meta, body };
}

function mergeGuides(guides: Guide[]): Guide[] {
  const merged = new Map<string, Guide>();
  for (const guide of guides) merged.set(guide.id, guide);
  return [...merged.values()].sort((a, b) => {
    const sourceRank = sourceWeight(a.source) - sourceWeight(b.source);
    if (sourceRank !== 0) return sourceRank;
    const kindRank = a.kind.localeCompare(b.kind);
    if (kindRank !== 0) return kindRank;
    return a.id.localeCompare(b.id);
  });
}

function sourceWeight(source: GuideSource): number {
  if (source === "workspace") return 0;
  if (source === "user") return 1;
  return 2;
}

function stringMeta(value: string | undefined, fallback: string): string {
  return value?.trim().replace(/^["']|["']$/g, "") || fallback;
}

function listMeta(value: string | undefined, fallback: string[]): string[] {
  if (!value) return fallback;
  return splitList(value.replace(/^\[|\]$/g, ""));
}

function splitList(value: string): string[] {
  return value.split(",").map((item) => item.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 50) || "custom-rule";
}

function oneLine(value: string): string {
  return value.replace(/\s+/g, " ").trim().slice(0, 140);
}

function limitLines(value: string, count: number): string {
  return value.split("\n").map((line) => line.trim()).filter(Boolean).slice(0, count).join("\n");
}
